## This is the solution jupyter notebook for Stae A Test

In [1]:
import pandas as pd
import numpy as np

Importing the dataset and reading it into a pandas Dataframe

In [2]:
Food_n_agric = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding="iso-8859-1")

In [3]:
Food_n_agric.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

11. What is the total sum of Animal Fat produced in 2014 and 2017 respectively?

In [4]:
Food_n_agric.groupby("Item")["Y2014", "Y2017"].sum().loc["Animal fats"]

C:\apps\anaconda3\envs\py3.0-TF2.0\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

Y2014    209460.54
Y2017    269617.53
Name: Animal fats, dtype: float64

12. What is the mean and standard deviation across the whole dataset for the year 2015 to 3 decimal places?

In [5]:
Food_n_agric.describe()["Y2015"][["mean", "std"]]

mean     135.235966
std     1603.403984
Name: Y2015, dtype: float64

13. What is the total number and percentage of missing data in 2016 to 2 decimal places?

In [6]:
missing_values_2016 = Food_n_agric.isnull().sum()["Y2016"]

In [7]:
Total_values_2016 = Food_n_agric["Y2016"].shape[0]
Total_values_2016

60943

In [8]:
percentage_null_2016 = missing_values_2016 / Total_values_2016 * 100
print(percentage_null_2016)

2.5187470259094566

14. Which year had the highest correlation with ‘Element Code’?

In [9]:
abs(Food_n_agric.corr()["Element Code"]).sort_values(ascending=True)

Area Code       0.000209
Y2016           0.023444
Y2015           0.023889
Y2017           0.024254
Y2018           0.024279
Y2014           0.024457
Item Code       0.024683
Element Code    1.000000
Name: Element Code, dtype: float64

15. What year has the highest sum of Import Quantity?

In [10]:
Food_n_agric.groupby("Element").sum()[["Y2014", "Y2015", "Y2016", "Y2017", "Y2018"]].loc["Import Quantity"]

Y2014    274144.48
Y2015    267018.46
Y2016    286582.78
Y2017    294559.09
Y2018    287997.09
Name: Import Quantity, dtype: float64

16. What is the total number of the sum of Production in 2014?

In [11]:
Food_n_agric.groupby("Element").sum()["Y2014"]

Element
Domestic supply quantity                  1996716.35
Export Quantity                            150020.64
Fat supply quantity (g/capita/day)          10225.56
Feed                                       216927.89
Food                                      1212332.49
Food supply (kcal/capita/day)              454257.00
Food supply quantity (kg/capita/yr)         49650.63
Import Quantity                            274144.48
Losses                                     153223.00
Other uses (non-food)                       78718.13
Processing                                 282923.00
Production                                1931287.75
Protein supply quantity (g/capita/day)      11836.46
Residuals                                   30149.00
Seed                                        21922.92
Stock Variation                             58749.83
Total Population - Both sexes             1031585.00
Tourist consumption                           416.00
Name: Y2014, dtype: float64

17. Which of these elements had the highest sum in 2018?

In [12]:
Food_n_agric[["Element", "Y2018"]].groupby("Element").sum()

                                             Y2018
Element
Domestic supply quantity                2161192.10
Export Quantity                          181594.80
Fat supply quantity (g/capita/day)        10258.69
Feed                                     233489.68
Food                                    1303841.28
Food supply (kcal/capita/day)            455261.00
Food supply quantity (kg/capita/yr)       49056.85
Import Quantity                          287997.09
Losses                                   163902.00
Other uses (non-food)                     91300.97
Processing                               308429.00
Production                              2075072.89
Protein supply quantity (g/capita/day)    11833.56
Residuals                                 34864.00
Seed                                      25263.14
Stock Variation                           20577.91
Total Population - Both sexes           1140605.00
Tourist consumption                          90.00

18. Which of these elements had the 3rd lowest sum in 2018?

In [13]:
Food_n_agric[["Element", "Y2018"]].groupby("Element").sum().sort_values(by="Y2018", ascending=True)

                                             Y2018
Element
Tourist consumption                          90.00
Fat supply quantity (g/capita/day)        10258.69
Protein supply quantity (g/capita/day)    11833.56
Stock Variation                           20577.91
Seed                                      25263.14
Residuals                                 34864.00
Food supply quantity (kg/capita/yr)       49056.85
Other uses (non-food)                     91300.97
Losses                                   163902.00
Export Quantity                          181594.80
Feed                                     233489.68
Import Quantity                          287997.09
Processing                               308429.00
Food supply (kcal/capita/day)            455261.00
Total Population - Both sexes           1140605.00
Food                                    1303841.28
Production                              2075072.89
Domestic supply quantity                2161192.10

19. What is the total Import Quantity in Algeria in 2018?

In [14]:
Food_n_agric.groupby(['Element', 'Area'])['Y2018'].aggregate('sum').unstack()

Area,Algeria,Angola,Benin,Botswana,Burkina Faso,Cabo Verde,Cameroon,Central African Republic,Chad,Comoros,...,Sierra Leone,South Africa,Sudan,Sudan (former),Togo,Tunisia,Uganda,United Republic of Tanzania,Zambia,Zimbabwe
Element,,,,,,,,,,,,,,,,,,,,,
Domestic supply quantity,90023.42,59590.22,31447.90,3045.85,25705.16,731.00,64009.74,5567.06,15489.73,19.95,...,12753.68,126493.86,65451.77,0.0,10000.22,31347.90,54617.10,92239.88,24994.80,17860.73
Export Quantity,811.54,7962.28,729.44,101.68,1088.16,42.99,1078.16,0.26,36.22,0.00,...,143.90,31630.62,1632.13,0.0,809.35,1649.87,4095.70,2289.77,1011.54,416.71
Fat supply quantity (g/capita/day),309.09,230.90,207.82,261.12,264.29,264.32,217.53,242.76,211.53,NaN,...,199.86,331.72,263.63,NaN,197.24,379.37,200.36,214.16,193.83,207.99
Feed,10668.00,7859.66,4662.54,28.04,1031.50,48.00,4857.24,5.00,1150.00,0.00,...,2170.00,12413.42,1887.00,0.0,1171.62,5621.70,297.04,4495.06,1950.66,141.32
Food,63736.33,37256.56,16209.34,2378.80,20525.63,572.99,35235.51,4457.06,9846.69,12.45,...,8444.68,61781.13,41857.77,0.0,7229.60,18901.69,41420.05,65741.38,12405.14,8821.37
Food supply (kcal/capita/day),13288.00,9538.00,11023.00,9365.00,10951.00,10164.00,10929.00,7141.00,8457.00,NaN,...,9476.00,11589.00,10309.00,NaN,9768.00,13804.00,7925.00,9487.00,8005.00,7627.00
Food supply quantity (kg/capita/yr),1509.28,1209.36,1411.42,1055.79,1039.07,1051.85,1397.30,955.84,636.12,NaN,...,1103.94,1068.97,1001.32,NaN,916.53,1634.21,969.43,1167.33,714.87,611.22
Import Quantity,36238.29,7769.67,7008.24,1908.42,2605.64,499.66,4188.88,75.02,491.95,2.92,...,1659.22,16192.45,9130.11,0.0,3625.48,11030.91,3209.87,1863.68,990.75,1673.84
Losses,7708.00,6135.00,2814.00,106.00,912.00,20.00,8742.00,293.00,1454.00,NaN,...,967.00,5576.00,5221.00,NaN,715.00,1747.00,1707.00,7538.00,1052.00,891.00
Other uses (non-food),3970.08,1014.00,4192.00,26.02,262.02,56.00,2111.00,48.00,0.04,7.50,...,268.00,1828.32,3615.00,0.0,234.00,346.51,85.02,1281.44,147.00,106.06
Processing,2479.00,6727.00,2148.00,196.00,2671.00,12.00,12248.00,636.00,1344.00,NaN,...,818.00,45681.00,12364.00,NaN,553.00,5136.00,10886.00,11894.00,9524.00,8300.00
Production,60766.67,59039.83,27500.54,1534.10,24859.68,297.36,61293.00,5601.28,15386.98,17.02,...,10642.38,139882.99,65336.79,0.0,9308.11,23075.85,54544.94,93182.97,24058.60,16161.60
Protein supply quantity (g/capita/day),367.28,212.20,255.90,263.26,320.57,283.43,287.57,178.29,245.98,NaN,...,204.07,337.47,291.87,NaN,233.85,399.16,187.74,235.74,242.08,176.57
Residuals,630.00,0.00,-66.00,300.00,-86.00,0.00,0.00,0.00,1410.00,NaN,...,-51.00,-1310.00,58.00,NaN,-230.00,-766.00,-86.00,-169.00,-254.00,-546.00
Seed,825.00,595.00,1487.00,11.00,396.00,2.00,819.00,131.00,288.00,NaN,...,129.00,517.00,451.00,NaN,330.00,360.00,314.00,1468.00,175.00,140.00
Stock Variation,6172.00,-743.00,2444.56,294.00,674.00,26.00,393.00,104.00,356.00,NaN,...,-597.00,-2018.98,7382.00,0.0,2121.00,1110.00,-955.00,521.00,-959.00,-447.00
Total Population - Both sexes,42228.00,30810.00,11485.00,2254.00,19751.00,544.00,25216.00,4666.00,15478.00,NaN,...,7650.00,57793.00,41802.00,NaN,7889.00,11565.00,42729.00,56313.00,17352.00,14439.00
Tourist consumption,NaN,0.00,NaN,0.00,NaN,7.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

20. What is the total number of unique countries in the dataset?

In [15]:
no_of_countries = len(Food_n_agric["Area"].unique())
print(no_of_countries)

49